### Variables
@baseUrl = http://localhost:5000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjFiMTRjY2Q4YTBkODQ5MDJiOWUwNCIsImlhdCI6MTc3MzI1NTkxOCwiZXhwIjoxNzc1ODQ3OTE4fQ.0ymrBzY5MtpjA22VbtEhr-1pHnT4keJ0Q9gIW_o-Fqs
### 1. Register a new user
POST {{baseUrl}}/users/register
Content-Type: application/json

    {
        "username": "Mike",
        "email": "mike@student.se",
        "password": "pastorsword123"
    }

### 2. Log in a user
POST {{baseUrl}}/users/login
Content-Type: application/json

    {
        "email": "mike@student.se",
        "password": "pastorsword123"
    }

### 3. Create movie(Token + Admin)
POST {{baseUrl}}/movies
Authorization: Bearer {{token}}
Content-Type: application/json

    {
        "title": "Home",
        "director": "Home",
        "releaseYear": 2018,
        "genre": "Anime"
    }

### 4. Get all movies
GET {{baseUrl}}/movies

### 5. Get movie by ID
GET {{baseUrl}}/movies/6979d36ae56b8220080afeda

### 6. Update movie (Admin Token)
PUT {{baseUrl}}/movies/6979d36ae56b8220080afeda
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Incr!",
    "director": "Molan",
    "releaseYear": 2016,
    "genre": "Horror"
}

### 7. Get reviews for a specific movie
GET {{baseUrl}}/movies/6979d36ae56b8220080afeda/reviews

### 8. Delete movie (Admin Token)
DELETE {{baseUrl}}/movies/6979d36ae56b8220080afeda
Authorization: Bearer {{token}}

### 9. Post a review for a movie (Token)
POST {{baseUrl}}/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

    {
        "movieId": "6979d36ae56b8220080afeda",
        "rating": 4,
        "comment": "Riktigt spännande film, rekommenderas!"
    }

### 10. Get all reviews
GET {{baseUrl}}/reviews

### 11. Get review by ID
GET {{baseUrl}}/reviews/69b1b87446a412a861f48103

### 12. Update review (Token)
PUT {{baseUrl}}/reviews/69b1b87446a412a861f48103
Authorization: Bearer {{token}}
Content-Type: application/json

    {
        "rating": 5,
        "comment": "En ännu bättre film!"
    }

### 13. Delete review (Token)
DELETE {{baseUrl}}/reviews/698058b5da587fe92674b292
Authorization: Bearer {{token}}

### 14.Get movies with ratings
GET {{baseUrl}}/movies/ratings
